version: '3.8'

services:
  app:
    build: .
    image: mi_p1_web:latest
    container_name: ${PREFIX_CONTENEDOR}_app
    restart: unless-stopped
    ports:
      - "${PUERTO_WEB}:1080"
    environment:
      - DB_HOST=db
      - DB_NAME=sistema_facturacion
      - DB_USER=comanda
      - DB_PASS=
    networks:
      - red_interna
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: ${PREFIX_CONTENEDOR}_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: sistema_facturacion
    ports:
      - "127.0.0.1:${PUERTO_DB}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_interna

  pma:
    image: phpmyadmin:latest
    container_name: ${PREFIX_CONTENEDOR}_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "${PUERTO_PMA}:80"
    networks:
      - red_interna
    depends_on:
      - db

networks:
  red_interna:
    driver: bridge

volumes:
  db_data:
    driver: local
